<!DOCTYPE html>
<html>
  <head>
    <title><?= $data['title'] ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/assets/gritter/css/jquery.gritter.css" rel="stylesheet" media="screen">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="/assets/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
  </head>
  <body ng-app="usersApp">
    <script src="/assets/jquery-1.9.1.min.js"></script>
    <script src="/assets/angular/angular.min.js"></script>
    <script src="/assets/angular/angular-resource.min.js"></script>
    <script src="/assets/bootbox/bootbox.min.js"></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/gritter/js/jquery.gritter.min.js"></script>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              Logged in as <a href="#" class="navbar-link">Username</a>
            </p>
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list" data-ng-controller="NavCtrl">
              <li class="nav-header">Sidebar</li>
              <li ng:class="{active: location.path() == '/users'}"><a href="#/users">Users</a></li>
              <li ng:class="{active: location.path() == '/systems'}"><a href="#/systems">Systems</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div data-ng-controller="RandomCtrl">
            <div>Seconds you've been on this page: {{counter}}</div>
          </div>
          <div ng-view></div>
          <?php //$this->yield($data) ?>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div><!--/.fluid-container-->
    <script src="/views/app.js"></script>
    <script src="/views/nav.js"></script>
    <script src="/views/users/users.js"></script>
    <script src="/views/systems.js"></script>
  </body>
</html>