<div data-ng-app="usersApp">
<div class="container">
  <div class="row">
    <div class="span3">
      <div data-ng-controller="RandomCtrl">
        <div>Seconds you've been on this page: {{counter}}</div>
      </div>
    </div>
    <div class="span9">
  <h1>Users</h1>
  <div data-ng-controller="UsersCtrl">
    <table ng-show="users.length">
      <thead>
        <tr><th>ID</th><th>Name</th></tr>
      </thead>
      <tbody>
        <tr ng-repeat="user in users">
          <td>{{user.id}}</td>
          <td>{{user.name}}</td>
          <td>
          <button class="btn" ng-click="deleteUser(user)"><i class="icon-trash"></i> Delete User</button>
          </td>
        </tr>
      </tbody>
    </table>
    <form ng-submit="createUser()">
      <div>Name <input type="text" ng-model="name" /></div>
      <div><button class="btn"><i class="icon-plus"></i> Create User</button></div>
      <div style="color: red;">{{nameError}}</div>
    </form>
  </div>
</div>
</div>
</div>
</div>

<link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.css" />
<script type="text/javascript" src="/assets/javascripts/jquery.js"></script>
<script type="text/javascript" src="/assets/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/assets/javascripts/angular.min.js"></script>
<script type="text/javascript" src="/assets/javascripts/angular-resource.min.js"></script>
<script type="text/javascript" src="/assets/javascripts/users.js"></script>
<script type="text/javascript" src="/assets/javascripts/bootbox.min.js"></script>
