<div data-ng-app="usersApp">
<div class="container">
  <div class="row">
    <div class="span3">
      <div data-ng-controller="RandomCtrl">
        <div>Seconds you've been on this page: {{counter}}</div>
      </div>
    </div>
    <div class="span9">
  <h1>Users</h1>
  <div data-ng-controller="UsersCtrl">
    <table ng-show="users.length">
      <thead>
        <tr><th>ID</th><th>Name</th></tr>
      </thead>
      <tbody>
        <tr ng-repeat="user in users">
          <td><a href="" ng-click="editUser(user)">{{user.id}}</a></td>
          <td>{{user.name}}</td>
          <td>
          <button class="btn btn-danger btn-mini" ng-click="deleteUser(user)"><i class="icon-trash"></i> Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
    <div ng-hide="userToEdit">
      <h3>New User</h3>
      <form ng-submit="createUser()">
        <div>Name <input type="text" ng-model="name" /></div>
        <div><button class="btn btn-primary"><i class="icon-plus"></i> Create User</button></div>
        <div style="color: red;">{{nameError}}</div>
      </form>
    </div>
    <div ng-show="userToEdit">
      <h3>Edit User</h3>
      <form ng-submit="updateUser()">
        <div>ID: {{userToEdit.id}}</div>
        <div>Name <input type="text" ng-model="userToEdit.name" /></div>
        <div>
          <button class="btn btn-primary">Edit User</button>
          <button class="btn" ng-click="cancelEdit()">Cancel</button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
</div>
</div>

<link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.css" />
<script type="text/javascript" src="/assets/javascripts/jquery.js"></script>
<script type="text/javascript" src="/assets/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/assets/javascripts/angular.min.js"></script>
<script type="text/javascript" src="/assets/javascripts/angular-resource.min.js"></script>
<script type="text/javascript" src="/assets/javascripts/users.js"></script>
<script type="text/javascript" src="/assets/javascripts/bootbox.min.js"></script>
