<div data-ng-app="usersApp">
<div class="container">
  <div class="row">
    <div class="span3">
      <div data-ng-controller="RandomCtrl">
        <div>Seconds you've been on this page: {{counter}}</div>
      </div>
    </div>
    <div class="span9">
  <h1>Users</h1>
  <div data-ng-controller="UsersCtrl">
    <table ng-show="users.length">
      <thead>
        <tr><th>Name</th></tr>
      </thead>
      <tbody>
        <tr ng-repeat="user in users">
          <td><a href="" ng-click="editUser(user)">{{user.name}}</a></td>
          <td>
          <button class="btn btn-danger btn-mini" ng-click="deleteUser(user)"><i class="icon-trash"></i> Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
    <div ng-hide="userToEdit">
      <h3>New User</h3>
      <form ng-submit="createUser()">
        <div>Name <input type="text" ng-model="name" /></div>
        <div><button class="btn btn-primary"><i class="icon-plus"></i> Create User</button></div>
        <div style="color: red;">{{nameError}}</div>
      </form>
    </div>
    <div ng-show="userToEdit">
      <h3>Edit User</h3>
      <form ng-submit="updateUser()">
        <div>ID: {{userToEdit.id}}</div>
        <div>Name <input type="text" ng-model="userToEdit.name" /></div>
        <div>
          <button class="btn btn-primary">Save</button>
          <button class="btn" ng-click="cancelEdit()">Cancel</button>
        </div>
      </form>
    </div>
    <div>
      <a href="/secure">Secure Area</a>
      <div ng-show="current_user">Logged in as {{current_user}} <button class="btn btn-mini" ng-click="logout()">Logout</button></div>
      <form ng-hide="current_user">
        <table class="table">
          <tbody>
            <tr>
              <td><label for='username'>Username</label></td>
              <td><input id='username' type='text' ng-model='username' /></td>
            </tr>
            <tr>
              <td><label for='password'>Password</label></td>
              <td><input id='password' type='password' ng-model='password' /></td>
            </tr>
            <tr>
              <td></td>
              <td><button class="btn btn-primary btn-mini" ng-click='login()'>Login</button></td>
            </tr>
          </tbody>
        </table>
      </form>
    </div>
  </div>
</div>
</div>
</div>
</div>

<link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.css" />
<script type="text/javascript" src="/assets/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/assets/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/assets/angular/angular.min.js"></script>
<script type="text/javascript" src="/assets/angular/angular-resource.min.js"></script>
<script type="text/javascript" src="/assets/bootbox/bootbox.min.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/gritter/css/jquery.gritter.css" />
<script type="text/javascript" src="/assets/gritter/js/jquery.gritter.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/toastmessage/css/jquery.toastmessage.css" />
<script type="text/javascript" src="/assets/toastmessage/js/jquery.toastmessage.js"></script>
<script type="text/javascript" src="/views/users/users.js"></script>